### ISSUE TITLE
When scrolling all the way to the bottom of the groups list there is one empty space

### ISSUE THREAD

**Issue by BrainStone** [Turbotailz/LuckPermsWeb#17]
![grafik](https://user-images.githubusercontent.com/4106544/63641642-0a40ad80-c6b2-11e9-8199-e8028655af30.png)

**Comment by Turbotailz** [comment]
This is intended, as the octocat icon overlaps the last item and can potentially hide content like a user's avatar or long group name.

**Comment by BrainStone** [comment]
I see. Fair point. Still looks odd.  
Maybe add something there to make it look intended and not just empty.
